{
 "id":"${this.ID}",
 "label":"${this.Label}",
 "icon":"${this.Icon}",
 "code_language":"${this.CodeLanguage}",
 "use_webbrowser":${this.UseWebbrowser},
 "use_database":${this.UseDatabase},
 "option":"${this.Option}",
 "scripts":[]
}